//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khruphanth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DisKH
    {
        public string TeaId { get; set; }
        public Nullable<int> TeaTitle { get; set; }
        public string TeaName { get; set; }
        public string RequisitionID { get; set; }
        public string Re_TeaId { get; set; }
        public string Re_StepID { get; set; }
        public int RequestLsitID { get; set; }
        public string RL_RequisitionID { get; set; }
        public string RL_NameKP { get; set; }
        public Nullable<double> RL_Price { get; set; }
        public string KhruphanthID { get; set; }
        public Nullable<int> Kh_RequestLsitID { get; set; }
        public Nullable<int> Kh_PlaceID { get; set; }
        public int PlaceID { get; set; }
        public string PL_NamePlace { get; set; }
        public string DistributorID { get; set; }
        public int DistributorList { get; set; }
        public string DL_DistributorID { get; set; }
        public string DL_KhruphanthID { get; set; }
        public string Di_Status { get; set; }
        public int TId { get; set; }
        public string TName { get; set; }
        public Nullable<System.DateTime> Re_DateRequi { get; set; }
        public Nullable<System.DateTime> Di_Date { get; set; }
        public string COPY_DATE { get; set; }
    }
}
