//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khruphanth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RemainRT_KH
    {
        public string RequisitionID { get; set; }
        public string TeaName { get; set; }
        public Nullable<System.DateTime> Re_DateRequi { get; set; }
        public string Re_StepID { get; set; }
        public int RequestLsitID { get; set; }
        public string RL_RequisitionID { get; set; }
        public string RL_NameKP { get; set; }
        public Nullable<double> RL_Amount { get; set; }
        public Nullable<double> RL_Price { get; set; }
        public string PL_NamePlace { get; set; }
        public string Converted { get; set; }
        public string TName { get; set; }
    }
}
